server:
  port: 8080

spring:
  # Startup logs
  main:
    banner-mode: off
    log-startup-info: off

  application:
    name: perfume_store

  # Datasource environments, imported by Intellij Envs Run Config in development
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  # JPA and Hibernate
  jpa:
    hibernate:
      ddl-auto: none  # Do nothing with the real schema when entities have changes
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # Tells Hibernate what SQL syntax db uses
